language: bash
services: docker

before_script:
- docker build -t amixsi/node:vue-cli-3 .

script:
- docker run --rm -it amixsi/node:vue-cli-3 npm version

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push amixsi/node